// ─────────────────────────────────────────────────────────────────────────────
// Blog Posts Collection — Liegeois Designs
// draft: true  → visible in dev, hidden in production
// draft: false → published
// ─────────────────────────────────────────────────────────────────────────────

import type { BlogPost } from './types'

export const blogPosts: BlogPost[] = [
  // ── Published ──────────────────────────────────────────────────────────────
  {
    slug: 'i-built-this-website-with-ai-heres-what-actually-happened',
    title: 'I Built This Website With AI. Here\'s What Actually Happened.',
    excerpt: 'A designer with no code, a dark room full of tools, and the learning curve nobody posts about — the vocabulary tax, the model maze, and what all the wasted evenings actually bought.',
    readTime: '9 min read',
    publishedAt: '2026-07-11',
    tags: ['AI & Design', 'Design Process', 'Personal'],
    theme: 'ai-in-design',
    draft: false,
    coverImage: 'https://res.cloudinary.com/dryyhpqew/image/upload/v1782077307/i_built_this_website_with_AI_cpg3pa.jpg',
  },
  {
    slug: 'big-picture-vision-tiny-picture-doubts',
    title: 'Big Picture Vision, Tiny Picture Doubts',
    excerpt: 'How fear paralyzes, and how micro-steps unlock courage.',
    readTime: '10 min read',
    publishedAt: '2025-11-05',
    tags: ['Creativity'],
    theme: 'breaking-free-from-the-script',
    draft: false,
    coverImage: 'https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/generated-image-august-29-2025-10-29am-81f5fb',
  },
  {
    slug: 'breaking-projects-into-scenes-not-steps',
    title: 'Breaking Projects into Scenes, Not Steps',
    excerpt: 'Why people remember stories, not checklists.',
    readTime: '10 min read',
    publishedAt: '2025-11-05',
    tags: ['Creativity', 'Storytelling'],
    theme: 'becoming-a-visual-storyteller',
    draft: false,
    coverImage: 'https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/generated-image-august-29-2025-10-32am-4538a1',
  },
  {
    slug: 'chaos-as-raw-material',
    title: 'Chaos as Raw Material',
    excerpt: 'Why ADHD thrives in disorder and how to make chaos fuel clarity.',
    readTime: '10 min read',
    publishedAt: '2025-11-05',
    tags: ['Creativity', 'Storytelling'],
    theme: 'adhd-as-a-creative-asset',
    draft: false,
    coverImage: 'https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/generated-image-august-29-2025-10-27am-039ed3',
  },
  {
    slug: 'designing-for-others-vs-designing-from-gut',
    title: 'Designing for Others vs. Designing from the Gut',
    excerpt: 'How to lead clients past "safe" into transformative work.',
    readTime: '10 min read',
    publishedAt: '2025-11-05',
    tags: ['Creativity'],
    theme: 'becoming-a-visual-storyteller',
    draft: false,
    coverImage: 'https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/generated-image-august-29-2025-9-42am-c93e6a',
  },
  {
    slug: 'embracing-storytelling-as-leadership',
    title: 'Embracing Storytelling as Leadership',
    excerpt: 'How leaders move people with narrative, not checklists.',
    readTime: '10 min read',
    publishedAt: '2025-11-05',
    tags: ['Storytelling'],
    theme: 'becoming-a-visual-storyteller',
    draft: false,
    coverImage: 'https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/generated-image-august-29-2025-10-56am-c70268',
  },
  {
    slug: 'neurodivergent-better-visual-storyteller',
    title: 'How Being Neuro-Divergent Makes Me a Better Visual Storyteller',
    excerpt: 'Pattern recognition as an ADHD superpower.',
    readTime: '10 min read',
    publishedAt: '2026-03-05',
    tags: ['Personal', 'Creativity', 'Storytelling'],
    theme: 'adhd-as-a-creative-asset',
    draft: false,
    coverImage: 'https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/generated-image-august-29-2025-10-31am-a751bb',
  },
  {
    slug: 'learning-to-speak-in-images',
    title: 'Learning to Speak in Images',
    excerpt: 'Growing up with photographer parents taught me that images speak faster than words.',
    readTime: '10 min read',
    publishedAt: '2025-11-05',
    tags: ['Presentation Design', 'Pitch Decks', 'Storytelling'],
    theme: 'becoming-a-visual-storyteller',
    draft: false,
    coverImage: 'https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/baby-aura-photos-2-0de408',
  },
  {
    slug: 'permission-slips-for-reinvention',
    title: 'Permission Slips for Reinvention',
    excerpt: "Stop waiting for diplomas, managers, or permission — write your own slip.",
    readTime: '10 min read',
    publishedAt: '2025-11-05',
    tags: ['Creativity'],
    theme: 'breaking-free-from-the-script',
    draft: false,
    coverImage: 'https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/generated-image-august-29-2025-9-29am-defa8d',
  },
  {
    slug: 'reinvention-after-breakdown',
    title: 'Reinvention After Breakdown',
    excerpt: 'How collapse became the doorway to creativity and truth.',
    readTime: '10 min read',
    publishedAt: '2025-11-05',
    tags: ['Creativity'],
    theme: 'breaking-free-from-the-script',
    draft: false,
    coverImage: 'https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/generated-image-august-29-2025-10-53am-4a9d6d',
  },
  {
    slug: 'the-art-of-presentation-as-persuasion',
    title: 'The Art of Presentation as Persuasion',
    excerpt: "Decks aren't slideshows — they're decisions in disguise.",
    readTime: '10 min read',
    publishedAt: '2025-11-05',
    tags: ['Pitch Decks', 'Storytelling', 'Presentation Design'],
    theme: 'presentation-design-tips',
    draft: false,
    coverImage: 'https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/generated-image-august-31-2025-2-54pm-1-eed3e6',
  },
  {
    slug: 'the-day-i-fired-my-inner-impostor-boss',
    title: 'The Day I Fired My "Inner Impostor Boss"',
    excerpt: 'How ADHD magnifies impostor syndrome and what it takes to shut it down.',
    readTime: '10 min read',
    publishedAt: '2025-11-05',
    tags: ['Creativity'],
    theme: 'adhd-as-a-creative-asset',
    draft: false,
    coverImage: 'https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/generated-image-august-29-2025-9-23am-66a544',
  },
  {
    slug: 'the-discipline-of-care',
    title: 'The Discipline of Care',
    excerpt: 'Why empathy and care are the ultimate creative edge.',
    readTime: '10 min read',
    publishedAt: '2025-11-05',
    tags: ['Creativity'],
    theme: 'lessons-for-fellow-travelers',
    draft: false,
    coverImage: 'https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/generated-image-august-29-2025-11-00am-ac8839',
  },
  {
    slug: 'the-first-time-i-saw-my-life-as-a-design-brief',
    title: 'The First Time I Saw My Life as a Design Brief',
    excerpt: 'A pain au chocolat as metaphor for life design: messy, intentional, and creative.',
    readTime: '10 min read',
    publishedAt: '2025-11-05',
    tags: ['Creativity'],
    theme: 'breaking-free-from-the-script',
    draft: false,
    coverImage: 'https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/pain-au-chocolat-64554a',
  },
  {
    slug: 'the-real-roi-of-presentation-design-for-startups',
    title: 'The Real ROI of Presentation Design for Startups',
    excerpt: 'A well-designed deck is the fastest path from pitch to funding.',
    readTime: '10 min read',
    publishedAt: '2025-11-05',
    tags: ['Pitch Decks', 'Presentation Design'],
    theme: 'presentation-design-tips',
    draft: false,
    coverImage: 'https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/roi-pitch-deck-startups-dc0e16',
  },
  {
    slug: 'what-success-looks-like',
    title: "What \"Success\" Looks Like When It's Not Yours",
    excerpt: "The danger of hitting all the wrong targets and why borrowed trophies don't count.",
    readTime: '10 min read',
    publishedAt: '2026-03-05',
    tags: ['Personal', 'Creativity'],
    theme: 'breaking-free-from-the-script',
    draft: false,
    coverImage: 'https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/generated-image-august-29-2025-9-32am-f9dcb3',
  },

  // ── Presentation Design Series (2026) ──────────────────────────────────────
  {
    slug: 'your-deck-has-a-story-problem',
    title: 'Your Deck Has a Story Problem (Not a Design Problem)',
    excerpt: 'Most presentations fail upstream of the design. Story architecture comes first, always — design is the last mile, not the foundation.',
    readTime: '8 min read',
    publishedAt: '2026-07-07',
    tags: ['Presentation Design', 'Storytelling'],
    theme: 'presentation-design-tips',
    draft: false,
    coverImage: 'https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/fivestone-20-20chevron-201-1-922e8d',
  },
  {
    slug: 'lead-with-the-outcome',
    title: 'Lead With the Outcome, Not the Agenda',
    excerpt: 'Your audience decides in the first 90 seconds whether the meeting was worth their time. Slide 1 is your entire argument, compressed.',
    readTime: '7 min read',
    publishedAt: '2026-07-14',
    tags: ['Presentation Design', 'Storytelling'],
    theme: 'presentation-design-tips',
    draft: false,
    coverImage: 'https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/marriott-the-luxury-group-slide-1-c397f7',
  },
  {
    slug: 'business-tension-in-presentations',
    title: 'The Business Tension Your Slides Are Ignoring',
    excerpt: 'Every great presentation has a tension — a gap between where things are and where they need to go. Without it, the deck has no spine.',
    readTime: '8 min read',
    publishedAt: '2026-07-21',
    tags: ['Presentation Design', 'Storytelling'],
    theme: 'presentation-design-tips',
    draft: false,
    coverImage: 'https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/portfolio-slides-rapp-evolus-pitch-deck-0007-19640a',
  },
  {
    slug: 'features-advantages-benefits',
    title: 'Features Are Facts. Benefits Are Why Anyone Cares.',
    excerpt: 'Your product does X. So what? The slide that wins isn\'t the one with more specs — it\'s the one that answers "what does this mean for me?"',
    readTime: '8 min read',
    publishedAt: '2026-07-28',
    tags: ['Presentation Design', 'Pitch Decks'],
    theme: 'presentation-design-tips',
    draft: false,
    coverImage: 'https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/portfolio-slides-philips-experience-intro-0001-052b0f',
  },
  {
    slug: 'rule-of-three-in-presentations',
    title: 'The Rule of Three Isn\'t Just a Writing Trick',
    excerpt: 'Every deck with seven key takeaways communicates zero. Structure is a memory device — and human memory runs on threes.',
    readTime: '7 min read',
    publishedAt: '2026-08-04',
    tags: ['Presentation Design', 'Storytelling'],
    theme: 'presentation-design-tips',
    draft: false,
    coverImage: 'https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/portfolio-slides-rapp-spectrum-0001-4046a6',
  },
  {
    slug: 'express-impact-in-kpis',
    title: 'If You Can\'t Say It in KPIs, You Haven\'t Earned the Ask',
    excerpt: 'Vague outcomes kill credibility. "Better engagement" means nothing to a CFO. Get specific or go home.',
    readTime: '8 min read',
    publishedAt: '2026-08-11',
    tags: ['Presentation Design', 'Pitch Decks'],
    theme: 'presentation-design-tips',
    draft: false,
    coverImage: 'https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/250418-connected-data-deck-update-use-this-version-edits-art-ae01b0',
  },
  {
    slug: 'know-your-audience-before-designing',
    title: 'The One Question Every Slide Must Answer Before You Design It',
    excerpt: 'Designing before you know your audience is like building a set without knowing the play.',
    readTime: '8 min read',
    publishedAt: '2026-08-18',
    tags: ['Presentation Design', 'Storytelling'],
    theme: 'presentation-design-tips',
    draft: false,
    coverImage: 'https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/portfolio-slides-philips-experience-intro-0003-a17bad',
  },
  {
    slug: 'presentation-altitude',
    title: 'Altitude: Why the Same Story Needs Three Different Decks',
    excerpt: 'An engineer, a VP, and a CEO need three different presentations — even if the core idea is identical.',
    readTime: '8 min read',
    publishedAt: '2026-08-25',
    tags: ['Presentation Design', 'Storytelling'],
    theme: 'presentation-design-tips',
    draft: false,
    coverImage: 'https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/250418-connected-data-deck-update-use-this-version-edits-art-0645fa',
  },
  {
    slug: 'connect-to-strategic-direction',
    title: 'Connect the Dots to What the Organization Already Believes',
    excerpt: 'The most persuasive thing you can say in a boardroom isn\'t "here\'s a new idea." It\'s "here\'s why this was already inevitable."',
    readTime: '7 min read',
    publishedAt: '2026-09-01',
    tags: ['Presentation Design', 'Storytelling'],
    theme: 'presentation-design-tips',
    draft: false,
    coverImage: 'https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/fivestone-chevron-5-a16654',
  },
  {
    slug: 'slides-as-speaker-support',
    title: 'Slides Don\'t Present Themselves. (But They Should Come Close.)',
    excerpt: 'If you can leave the room and your audience can understand your deck on their own — you\'ve built a PDF, not a presentation.',
    readTime: '7 min read',
    publishedAt: '2026-09-08',
    tags: ['Presentation Design', 'Storytelling'],
    theme: 'presentation-design-tips',
    draft: false,
    coverImage: 'https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/230427-echo-society-deck-2-0-slide-1-a2020d',
  },
  {
    slug: 'think-like-a-filmmaker',
    title: 'Think Like a Filmmaker. Design Like a Director.',
    excerpt: 'Your deck has 22 slides. A film has 1,200 shots. Both are trying to do the same thing: get the audience to feel something at the right moment.',
    readTime: '9 min read',
    publishedAt: '2026-09-15',
    tags: ['Presentation Design', 'Storytelling'],
    theme: 'presentation-design-tips',
    draft: false,
    coverImage: 'https://res.cloudinary.com/dryyhpqew/image/upload/v1782075443/think_like_a_filmmaker_fgaps0.jpg',
  },
  {
    slug: 'less-is-more-in-presentations',
    title: 'Why the Most Memorable Presentations Have Almost Nothing on Them',
    excerpt: 'Every slide that didn\'t make it into the final deck made the final deck better. Subtraction is a design skill.',
    readTime: '7 min read',
    publishedAt: '2026-09-22',
    tags: ['Presentation Design', 'Storytelling'],
    theme: 'presentation-design-tips',
    draft: false,
    coverImage: 'https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/portfolio-slides-university-startups-pitch-deck-0001-8eedd5',
  },

  // ── Drafts ─────────────────────────────────────────────────────────────────
  {
    slug: 'corporate-costume-creative-skin',
    title: 'From Corporate Costume to Thin Creative Skin',
    excerpt: 'Why hiding behind conformity kills originality and how authenticity is your new armor.',
    readTime: '10 min read',
    publishedAt: '2025-11-05',
    tags: ['Creativity'],
    theme: 'breaking-free-from-the-script',
    draft: true,
    coverImage: 'https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/generated-image-august-29-2025-9-26am-d4710e',
  },
  {
    slug: 'the-moment-i-made-things-undeniable',
    title: 'The Moment I Made Things Undeniable (Not Just Pretty)',
    excerpt: 'When design stops being decoration and starts being persuasion.',
    readTime: '10 min read',
    publishedAt: '2025-11-05',
    tags: ['Personal', 'Creativity'],
    theme: 'presentation-design-tips',
    draft: true,
    coverImage: 'https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/generated-image-august-29-2025-10-26am-b23680',
  },
  {
    slug: 'the-myth-playing-safe',
    title: 'The Myth of Playing It Safe (and Why It Costs More Than Risk)',
    excerpt: 'Why compliance kills impact and how tested boldness wins respect.',
    readTime: '10 min read',
    publishedAt: '2025-11-05',
    tags: ['Strategy'],
    theme: 'lessons-for-fellow-travelers',
    draft: true,
    coverImage: 'https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/generated-image-august-29-2025-9-50am-c55e56',
  },
  {
    slug: 'living-someone-else-story',
    title: "When You Realize You're Living Someone Else's Story",
    excerpt: 'The mirror moment of breaking free from borrowed lives and borrowed metrics.',
    readTime: '10 min read',
    publishedAt: '2026-03-05',
    tags: ['Personal', 'Creativity'],
    theme: 'breaking-free-from-the-script',
    draft: true,
    coverImage: 'https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/generated-image-august-29-2025-9-19am-777f6d',
  },
]

/** Published posts only, sorted newest first */
export const publishedPosts = blogPosts
  .filter((p) => !p.draft)
  .sort((a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime())

/** Latest N posts (for homepage blog section) */
export function getLatestPosts(count = 3): BlogPost[] {
  const posts =
    process.env.NODE_ENV === 'development' ? blogPosts : publishedPosts
  return posts.slice(0, count)
}
