// ─────────────────────────────────────────────────────────────
// GENERATED by scripts/gen-home-data.mjs — do not edit by hand.
// Light work data for the homepage bundle (full text stays out of it).
// Rerun after editing case-studies.ts:  node scripts/gen-home-data.mjs
// ─────────────────────────────────────────────────────────────

export type WorkLite = {
  slug: string
  client: string
  project: string
  format: string
  year: number
  image: string
}

export const TOTAL_PROJECTS = 36

export const featuredWork: WorkLite[] = [
  {
    "slug": "chevron-new-energies",
    "client": "Chevron New Energies",
    "project": "New Energies Strategic Narrative",
    "format": "Executive Presentation",
    "year": 2025,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/fivestone-20-20chevron-201-1-922e8d"
  },
  {
    "slug": "marriott-luxury-group",
    "client": "Marriott Luxury Group",
    "project": "YouTube Content Strategy 2025",
    "format": "Executive Presentation",
    "year": 2025,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/marriott-the-luxury-group-slide-1-c397f7"
  },
  {
    "slug": "echo-society",
    "client": "Echo Society",
    "project": "Brand & Culture Storytelling Deck",
    "format": "Pitch & Investor Deck",
    "year": 2024,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/221114-echo-society-show-009-001-12c35c"
  },
  {
    "slug": "the-spaceship",
    "client": "The Spaceship",
    "project": "Investor Deck",
    "format": "Pitch & Investor Deck",
    "year": 2024,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/spaceship-01.jpg"
  },
  {
    "slug": "mcs-healthcare-jandj",
    "client": "MCS Healthcare × J&J",
    "project": "Internal Achievements Presentation",
    "format": "Sales & Agency Deck",
    "year": 2024,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/mcs-jj-01.jpg"
  }
]

export const workLiteBySlug: Record<string, WorkLite> = Object.fromEntries(
  ([
  {
    "slug": "chevron-new-energies",
    "client": "Chevron New Energies",
    "project": "New Energies Strategic Narrative",
    "format": "Executive Presentation",
    "year": 2025,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/fivestone-20-20chevron-201-1-922e8d"
  },
  {
    "slug": "marriott-luxury-group",
    "client": "Marriott Luxury Group",
    "project": "YouTube Content Strategy 2025",
    "format": "Executive Presentation",
    "year": 2025,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/marriott-the-luxury-group-slide-1-c397f7"
  },
  {
    "slug": "echo-society",
    "client": "Echo Society",
    "project": "Brand & Culture Storytelling Deck",
    "format": "Pitch & Investor Deck",
    "year": 2024,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/221114-echo-society-show-009-001-12c35c"
  },
  {
    "slug": "the-spaceship",
    "client": "The Spaceship",
    "project": "Investor Deck",
    "format": "Pitch & Investor Deck",
    "year": 2024,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/spaceship-01.jpg"
  },
  {
    "slug": "mcs-healthcare-jandj",
    "client": "MCS Healthcare × J&J",
    "project": "Internal Achievements Presentation",
    "format": "Sales & Agency Deck",
    "year": 2024,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/mcs-jj-01.jpg"
  },
  {
    "slug": "philips-healthcare",
    "client": "Philips Healthcare",
    "project": "Healthcare Technology Presentation",
    "format": "Executive Presentation",
    "year": 2024,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/portfolio-slides-philips-experience-intro-0001-052b0f"
  },
  {
    "slug": "intercept-pharma",
    "client": "Intercept Pharmaceuticals",
    "project": "POA Field Training — Strong Foundation",
    "format": "Training Presentation",
    "year": 2024,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/portfolio-slides-toddstreet-intercept-oca-aug-training-0001-ddc7f1"
  },
  {
    "slug": "rapp-opmg",
    "client": "OPMG × RAPP",
    "project": "Connected Data Deck",
    "format": "Sales & Agency Deck",
    "year": 2025,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/250418-connected-data-deck-update-use-this-version-edits-art-ae01b0"
  },
  {
    "slug": "underpin",
    "client": "Underpin",
    "project": "Startup Pitch Deck",
    "format": "Pitch & Investor Deck",
    "year": 2023,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/screenshot-underpin-7af498"
  },
  {
    "slug": "university-startups",
    "client": "University Startups",
    "project": "Pitch Deck — A Better Future for Students",
    "format": "Pitch & Investor Deck",
    "year": 2022,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/portfolio-slides-university-startups-pitch-deck-0001-8eedd5"
  },
  {
    "slug": "mcs-healthcare-lupus",
    "client": "Lupus Association × JPMorgan",
    "project": "Lupus Awareness Campaign Deck",
    "format": "Executive Presentation",
    "year": 2024,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/MCS-Healthcare-Lupus-JPM-01.jpg"
  },
  {
    "slug": "rapp-spectrum-enterprise",
    "client": "Spectrum Enterprise × RAPP",
    "project": "Creative Immersion Session",
    "format": "Sales & Agency Deck",
    "year": 2023,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/portfolio-slides-rapp-spectrum-0001-4046a6"
  },
  {
    "slug": "projectbe-colorcode",
    "client": "ProjectBe — ColorCode",
    "project": "Brand Pitch Deck",
    "format": "Pitch & Investor Deck",
    "year": 2023,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/portfolio-slides-projectbe-colorcode-workshop-0003-0b4ec6"
  },
  {
    "slug": "rapp-and-evolus",
    "client": "Evolus",
    "project": "A Lifestyle-Driven Pharma Pitch Deck That Breaks the Mold",
    "format": "Pitch & Investor Deck",
    "year": 2023,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/portfolio-slides-rapp-evolus-pitch-deck-0007-19640a"
  },
  {
    "slug": "special-forces-project-starzplay",
    "client": "Starz",
    "project": "Special Forces Insights for StarzPlay UK",
    "format": "Executive Presentation",
    "year": 2023,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/slide1-83589e"
  },
  {
    "slug": "the-special-event-company-20-b7a3c",
    "client": "The Special Event Company",
    "project": "The Special Event Company Capabilities Fully Animated Deck",
    "format": "Sales & Agency Deck",
    "year": 2023,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/portfolio-slides-the-special-event-company-capabilities-deck-61be5a"
  },
  {
    "slug": "sunrise-cellars",
    "client": "Sunrise Cellars",
    "project": "Rebranding Old Wine Stores to Become a Future-proof high-end, One-Stop Shop for Wine Lovers",
    "format": "Strategic Narrative",
    "year": 2025,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/sunrise-cellars-storefront-2-adac1d"
  },
  {
    "slug": "adm-prod-tgi-fridays-campaign",
    "client": "TGI Fridays Franchisor, LLC",
    "project": "Designing Impactful Visuals for a Food Franchisor's Keynote Event",
    "format": "Training Presentation",
    "year": 2023,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/adm-prod-tgif-img-1-8f65e6"
  },
  {
    "slug": "norigami-brand",
    "client": "Norigami",
    "project": "Designing a Full Food Startup Brand that Looks just like an Established Company",
    "format": "Strategic Narrative",
    "year": 2016,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/norigami16361blackjpeg-87030e"
  },
  {
    "slug": "foodspace-lunch-learn-robotics",
    "client": "FoodSpace",
    "project": "Designing a Lunch & Learn Keynote for Architects: How Technology will change to ",
    "format": "Training Presentation",
    "year": 2021,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/foodspace-201-1-6d6fea"
  },
  {
    "slug": "grey-slide-sample-1-8439d",
    "client": "Post Consumer Brands",
    "project": "Designing a New Business Pitch Deck for a huge FMCG Brand",
    "format": "Pitch & Investor Deck",
    "year": 2023,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/220216-grey-mini-brief-arthur-liegeois-001-f580a6"
  },
  {
    "slug": "ogilvy-for-cdw-1-98a9e",
    "client": "CDW",
    "project": "Designing a New Business Pitch Deck to online tech store CDW",
    "format": "Pitch & Investor Deck",
    "year": 2023,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/portfolio-slides-ogilvy-cdw-0001-2ddadb"
  },
  {
    "slug": "international-advertising-association",
    "client": "IAA",
    "project": "Designing a new homepage for high-level marketing community event producers",
    "format": "Strategic Narrative",
    "year": 2024,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/iaa-website-figma-slide1-501f7e"
  },
  {
    "slug": "bloomberg-media-internal-dei-strategy",
    "client": "Bloomberg Media Group",
    "project": "Designing a fully detailed Internal DE&I Strategy Deck for the C-Suite",
    "format": "Executive Presentation",
    "year": 2023,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/bloomberg-25201-1-e75aa4"
  },
  {
    "slug": "norigami-slide-1-7cc23",
    "client": "Norigami",
    "project": "Designing an Engaging Investor Pitch Deck for a Food Startup that closed the deal.",
    "format": "Pitch & Investor Deck",
    "year": 2019,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/220104-static-image-7547d3"
  },
  {
    "slug": "project-be-project-wellness-keynote",
    "client": "Project Be",
    "project": "Designing an Engaging, Fully Animated, Digital Wellness Keynote",
    "format": "Training Presentation",
    "year": 2023,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/portfolio-slides-projectbe-digital-wellness-conference-0002-2291f7"
  },
  {
    "slug": "echo-society-pitch-deck-2",
    "client": "Echo Society",
    "project": "Designing an Investor-Ready Startup Pitch Deck, Pt. 1",
    "format": "Pitch & Investor Deck",
    "year": 2024,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/echo-2520society-25201-1-10981f"
  },
  {
    "slug": "foodspace-sales-deck",
    "client": "FoodSpace",
    "project": "Designing an engaging Sales Deck in Foodservice",
    "format": "Sales & Agency Deck",
    "year": 2022,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/210604-foodspace-deck-001-17ef77"
  },
  {
    "slug": "the-be-curious-group-iot-workshop",
    "client": "The Be Curious Group",
    "project": "Designing and Delivering a Training Deck to Explain the IoT to Female Entrepreneurs",
    "format": "Training Presentation",
    "year": 2020,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/tbcg-iot-slide-0-9e03ab"
  },
  {
    "slug": "ibm-quantum-summit-2022-cn3q3",
    "client": "IBM Quantum",
    "project": "IBM Quantum Summit 2022 Keynote",
    "format": "Training Presentation",
    "year": 2022,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/portfolio-slides-ibm-quantum-summit-0001-1ddb8b"
  },
  {
    "slug": "special-forces-project-google",
    "client": "Google",
    "project": "Special Forces Insights Deck for Google",
    "format": "Executive Presentation",
    "year": 2023,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/screenshot-25202024-10-05-2520at-252009-03-39-c61d89"
  },
  {
    "slug": "toddstreet-intercept-regional-sales-training",
    "client": "Intercept Pharmaceuticals",
    "project": "ToddStreet for Intercept",
    "format": "Training Presentation",
    "year": 2024,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/portfolio-slides-toddstreet-intercept-oca-aug-training-0001-ddc7f1"
  },
  {
    "slug": "mcs-healthcare-public-relations-2",
    "client": "MCS Healthcare",
    "project": "Rebranding and Modernizing the Look and Feel of an Established, Healthcare-focused PR Agency ",
    "format": "Strategic Narrative",
    "year": 2025,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/asset-2016-fa7eae"
  },
  {
    "slug": "mcs-healthcare-public-relations",
    "client": "MCS Healthcare PR",
    "project": "Redesigning the Website of an established PR Agency expert in Healthcare",
    "format": "Strategic Narrative",
    "year": 2025,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/mcs-webp-1-6f8d5e"
  },
  {
    "slug": "adm-productions-emd-1-c6815",
    "client": "EMD Group Serono",
    "project": "EMD Serono Group 2024 MA&PS Summit",
    "format": "Training Presentation",
    "year": 2023,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/portfolio-slides-adm-productions-emd-0010-c7d828"
  },
  {
    "slug": "ogilvy-for-mastercard-1",
    "client": "Mastercard",
    "project": "“Discover the Priceless in Us\" High level, New Business Pitch Deck",
    "format": "Pitch & Investor Deck",
    "year": 2022,
    "image": "https://res.cloudinary.com/dryyhpqew/image/upload/f_auto,q_auto/liegeois-designs/webflow/ogilvy-mastercard-pitch-deck-001-9dc112"
  }
] as WorkLite[]).map((w) => [w.slug, w]),
)
